
-- Drop data
delete from Items;
delete from Crosswords;
delete from Neighbors;
delete from Words;

-- Add some words
insert into Words values
	(0, 'ABERDONIAN'),
	(1, 'ABLATION'),
	(2, 'ARSONIST'),
	(3, 'ARUMDO'),
	(4, 'BLUEBOTTLE'),
	(5, 'BOLERO'),
	(6, 'BOTHERED'),
	(7, 'CABINCREW'),
	(8, 'CAFE'),
	(9, 'CANE'),
	(10, 'CONFETTI'),
	(11, 'COVET'),
	(12, 'DAIL'),
	(13, 'DRAWER'),
	(14, 'EROSIVE'),
	(15, 'FETCHING'),
	(16, 'FLOUNDER'),
	(17, 'HARLOW'),
	(18, 'HEMISPHERICAL'),
	(19, 'HID'),
	(20, 'HUM'),
	(21, 'ILTROVATORE'),
	(22, 'INSPADES'),
	(23, 'LEGALIST'),
	(24, 'LETSGO'),
	(25, 'LOLLIPOPS'),
	(26, 'MEAGRE'),
	(27, 'MIASMA'),
	(28, 'MINDFUL'),
	(29, 'MISSIVES'),
	(30, 'MONITOR'),
	(31, 'NARCOSIS'),
	(32, 'PENTAD'),
	(33, 'PTOMAINE'),
	(34, 'PUNCHEON'),
	(35, 'RABBI'),
	(36, 'RAGE'),
	(37, 'RAPIER'),
	(38, 'RAREFIED'),
	(39, 'RAVEL'),
	(40, 'REBEL'),
	(41, 'RIFLEMAN'),
	(42, 'ROOF'),
	(43, 'SEES'),
	(44, 'SITE'),
	(45, 'SLAVISH'),
	(46, 'SOLEMN'),
	(47, 'SPECIAL'),
	(48, 'SPUR'),
	(49, 'SUDDENDEATH'),
	(50, 'TANGELO'),
	(51, 'WELLTRAVELLED');

-- Add some crosswords
insert into Crosswords values
	(0, 'The Guardian', 'eng', 'Quick crossword No 13,988', 'http://www.theguardian.com/crosswords/quick/13988', null, '2015-03-10', null),
	(1, 'The Guardian', 'eng', 'Cryptic crossword No 26,482', 'http://www.theguardian.com/crosswords/cryptic/26482', null, '2015-01-30', null);
	
-- Add their items
insert into Items values
	(0, 31, 0, 8, 'Unconsciousness induced by drugs (8)', 'East'),
	(0, 28, 2, 0, 'Taking care (7)', 'South'),
	(0, 40, 2, 8, 'Kick over the traces (5)', 'South'),
	(0, 9, 8, 9, 'Walking stick (4)', 'South'),
	(0, 25, 12, 0, 'Sweets — popular works of classical music (9)', 'South'),
	(0, 10, 5, 4, 'Bits of paper scattered at festive occasions (8)', 'East'),
	(0, 5, 0, 6, 'Dance — work by 9 (6)', 'East'),
	(0, 39, 8, 2, 'Make more complicated — French composer, d. 1937 (5)', 'East'),
	(0, 43, 9, 8, 'Notices (4)', 'East'),
	(0, 35, 0, 10, 'Jewish minister (5)', 'East'),
	(0, 19, 12, 10, 'Concealed oneself (3)', 'South'),
	(0, 24, 7, 6, 'Liberates (4,2)', 'East'),
	(0, 7, 0, 4, 'Flight attendants (5,4)', 'South'),
	(0, 51, 0, 12, 'Having seen a lot of the world (4,9)', 'East'),
	(0, 11, 10, 0, 'Wish for something (5)', 'South'),
	(0, 27, 6, 7, 'Unwholesome atmosphere (6)', 'South'),
	(0, 18, 0, 0, 'Domed (13)', 'East'),
	(0, 17, 6, 0, 'Essex town — American film actress, d. 1937 (6)', 'South'),
	(0, 20, 0, 0, 'Smell badly (slang) (3)', 'South'),
	(0, 8, 0, 4, 'Greasy spoon (4)', 'East'),
	(0, 38, 8, 0, 'Grand — with low density (8)', 'South'),
	(0, 45, 6, 10, 'Abjectly submissive (7)', 'East'),
	(0, 44, 4, 0, 'Position (4)', 'South'),
	(0, 47, 10, 6, 'Important (7)', 'South'),
	(0, 30, 0, 2, 'School pupil assigned responsibilities (7)', 'East'),
	(0, 2, 4, 5, 'Pyromaniac (8)', 'South'),
	(1, 50, 8, 7, 'Fruit to set around throne? (7)', 'East'),
	(1, 14, 0, 7, 'Following pagan god, this writer has to be caustic (7)', 'East'),
	(1, 4, 8, 0, 'Fly low with courage (10)', 'South'),
	(1, 42, 2, 10, 'Page from mathematical demonstration that may go over one''s head (4)', 'South'),
	(1, 48, 0, 10, 'Prompt jet has cut time (4)', 'South'),
	(1, 13, 10, 9, 'Artist showing a bit of chest', 'South'),
	(1, 12, 12, 1, 'Irish house cleaner with no end of blarney (4)', 'South'),
	(1, 16, 7, 1, 'Struggle, having run aground crossing lake (8)', 'East'),
	(1, 37, 9, 11, 'Turned back when pierced by very good sword (6)', 'East'),
	(1, 21, 0, 5, 'Traitor mixed up with love in opera (2,9)', 'East'),
	(1, 46, 0, 3, 'About original moon-lander, boy gets serious (6)', 'East'),
	(1, 49, 4, 9, 'Dad enthused about extra period of play (6,5)', 'East'),
	(1, 26, 0, 1, 'Pasquale given less than full assent? That''s mean! (6)', 'East'),
	(1, 41, 0, 13, 'Soldier runs, if pursued by old lover (8)', 'East'),
	(1, 22, 4, 7, 'Decidedly snide, nasty about Harrogate, say (2,6)', 'South'),
	(1, 23, 12, 6, 'Stickler getting on with the most celebrated people (8)', 'South'),
	(1, 29, 0, 1, 'Fails to pen four letters, maybe (8)', 'South'),
	(1, 3, 4, 0, 'Fuss about drink — situation causing disapproval? (1,3,2)', 'South'),
	(1, 15, 7, 3, 'Attractive task for one on an errand? (8)', 'East'),
	(1, 1, 2, 1, 'Removal of a charitable offering presented without love (8)', 'South'),
	(1, 32, 9, 13, 'Ten awkward in accommodation for five (6)', 'East'),
	(1, 33, 0, 11, 'Self-consumed radical polemicist producing poisonous stuff (8)', 'East'),
	(1, 34, 10, 0, 'Drink a very long time — one has several gallons (8)', 'South'),
	(1, 36, 14, 1, 'Student event with energy and passion (4)', 'South'),
	(1, 0, 6, 5, 'Scot had one bairn, struggling without husband (10)', 'South'),
	(1, 6, 14, 6, 'Troubled and more like an invalid, it seems (8)', 'South');

